{{- if .Values.master.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "tmate.fullname" . }}-master
  labels:
    app: tmate-master
    app.kubernetes.io/part-of: tmate
    {{- include "tmate.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "tmate.fullname" . }}-master
  minReplicas: {{ .Values.master.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.master.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.master.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.master.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.master.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.master.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
