{{- if .Values.admin.ingress.enabled -}}
{{- $fullName := include "powerdns.fullname" . -}}
{{- $svcPort := .Values.admin.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
{{- if eq .Values.admin.ingress.class "traefik" }}
  annotations:
    {{- toYaml .Values.admin.ingress.annotations }}
{{- end }}
{{- if eq .Values.admin.ingress.class "nginx" }}
  annotations:
    kubernetes.io/ingress.class: nginx
{{- end }}
spec:
{{- if .Values.admin.ingress.tls }}
  tls:
  {{- range .Values.admin.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: {{ .Values.admin.ingress.hostname }}.{{ .Values.powerdns.domain }}
      http:
        paths:
          - path: {{ .Values.admin.ingress.path | quote }}
            backend:
              serviceName: {{ $fullName }}-service-admin
              servicePort: {{ $svcPort }}
{{- end }}
